
import React, { useState, useEffect, useRef } from 'react';
import { TacticalCard } from '../components/TacticalCard';
import { ViewHeader } from '../components/ViewHeader';
import Modal from '../components/Modal';
import { 
  Cable, FileText, Globe, Cloud, Database, 
  UploadCloud, Plus, Trash2, Key, Lock, 
  Settings, Bot, BrainCircuit,
  AlertTriangle, RefreshCw, Layers, MessageSquare, 
  HeartPulse, File as FileIcon,
  FileCode, Copy, Check,
  Shield, Send, User, ChevronLeft, Wifi, WifiOff, Zap,
  Building2, ShieldAlert, ShieldCheck, Activity, XCircle, Save, Eye, EyeOff, Server,
  Table, Workflow, Briefcase, Stethoscope, Leaf, Search, PlayCircle, Clock, Calendar, CheckCircle2
} from 'lucide-react';
import { 
    DataSourceFile, DataSourceWeb, DataSourceAPI, TelegramBotConfig, LLMConfig, IntegrationSecret,
    DataCatalogItem, UserDatasetTemplate, AutoGeneratedDataset, WizardData, DataSector
} from '../types';
import { api } from '../services/api';

// --- SUB-COMPONENTS ---

interface SecretRowProps {
    secret: IntegrationSecret;
    onTest: (s: IntegrationSecret) => void;
    onSave: (s: IntegrationSecret, val: string) => void;
}

const SecretRow: React.FC<SecretRowProps> = ({ secret, onTest, onSave }) => {
    const [isVisible, setIsVisible] = useState(false);
    const [value, setValue] = useState('');
    const [isEdited, setIsEdited] = useState(false);

    return (
        <div className="bg-slate-950 border border-slate-800 rounded p-4 flex flex-col md:flex-row items-start md:items-center gap-4 transition-colors hover:border-slate-700 panel-3d">
            <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                    <h4 className="text-sm font-bold text-slate-200">{secret.name}</h4>
                    <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold uppercase ${
                        secret.category === 'GOV' ? 'bg-blue-900/20 text-blue-400 border border-blue-900/50' :
                        secret.category === 'LLM' ? 'bg-purple-900/20 text-purple-400 border border-purple-900/50' :
                        secret.category === 'BOT' ? 'bg-cyan-900/20 text-cyan-400 border border-cyan-900/50' :
                        secret.category === 'CYBER' ? 'bg-red-900/20 text-red-400 border border-red-900/50' :
                        secret.category === 'INFRA' ? 'bg-orange-900/20 text-orange-400 border border-orange-900/50' :
                        'bg-slate-800 text-slate-400'
                    }`}>
                        {secret.category}
                    </span>
                    {secret.isCritical && (
                        <span title="Critical Infrastructure" className="inline-block align-middle">
                            <ShieldAlert size={14} className="text-red-500" />
                        </span>
                    )}
                </div>
                <div className="text-xs text-slate-500 font-mono flex items-center gap-2">
                    <span className="bg-slate-900 px-1.5 rounded text-primary-500">{secret.keyName}</span>
                    <span className="text-slate-600">|</span>
                    <span className="truncate max-w-[200px]" title={secret.vaultPath}>vault:{secret.vaultPath}</span>
                </div>
            </div>

            <div className="flex-1 w-full md:w-auto relative group">
                {secret.requiresFile ? (
                    <div className="flex gap-2">
                        <button className="flex-1 bg-slate-900 border border-slate-700 rounded px-3 py-2 text-[10px] text-slate-300 hover:text-white hover:border-slate-500 transition-all flex items-center justify-center gap-2">
                            <UploadCloud size={12} /> Upload Key File
                        </button>
                    </div>
                ) : (
                    <div className="relative">
                        <input 
                            type={isVisible ? "text" : "password"}
                            value={value}
                            onChange={(e) => { setValue(e.target.value); setIsEdited(true); }}
                            placeholder={secret.status === 'ACTIVE' ? '•••••••••••••••••••••' : 'Enter Secret Key...'}
                            className={`w-full bg-slate-900 border rounded px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-primary-500 font-mono transition-all ${isEdited ? 'border-primary-500/50' : 'border-slate-700'}`}
                        />
                        <button 
                            onClick={() => setIsVisible(!isVisible)}
                            className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-white"
                        >
                            {isVisible ? <EyeOff size={12} /> : <Eye size={12} />}
                        </button>
                    </div>
                )}
            </div>

            <div className="flex items-center gap-2 w-full md:w-auto justify-end">
                <div className="flex flex-col items-end mr-2">
                    <span className={`text-[10px] font-bold uppercase ${
                        secret.status === 'ACTIVE' ? 'text-success-500' :
                        secret.status === 'INVALID' ? 'text-red-500' :
                        secret.status === 'SYNCING' ? 'text-blue-400 animate-pulse' :
                        'text-yellow-500'
                    }`}>
                        {secret.status}
                    </span>
                    <span className="text-[9px] text-slate-600 font-mono">{secret.lastChecked || 'Never'}</span>
                </div>
                
                <button 
                    onClick={() => onTest(secret)}
                    className="p-2 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white rounded border border-slate-700 transition-all btn-3d"
                    title="Test Connection"
                >
                    <RefreshCw size={14} />
                </button>
                
                <button 
                    onClick={() => { onSave(secret, value); setValue(''); setIsEdited(false); }}
                    disabled={!isEdited}
                    className="p-2 bg-primary-600 hover:bg-primary-500 text-white rounded shadow-lg disabled:opacity-50 disabled:cursor-not-allowed transition-all btn-3d btn-3d-blue"
                    title="Save to Vault"
                >
                    <Save size={14} />
                </button>
            </div>
        </div>
    );
};

const WizardStep = ({ num, title, active, completed }: { num: number, title: string, active: boolean, completed: boolean }) => (
    <div className={`flex flex-col items-center gap-2 relative z-10 w-24`}>
        <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 font-bold text-xs transition-all ${
            active ? 'bg-primary-500 border-primary-500 text-white shadow-[0_0_15px_#06b6d4]' : 
            completed ? 'bg-success-500 border-success-500 text-slate-900' : 
            'bg-slate-900 border-slate-700 text-slate-500'
        }`}>
            {completed ? <Check size={14} /> : num}
        </div>
        <span className={`text-[10px] uppercase font-bold text-center ${active ? 'text-primary-400' : completed ? 'text-success-500' : 'text-slate-600'}`}>{title}</span>
    </div>
);

// --- MAIN COMPONENT ---

const IntegrationView: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'SOURCES' | 'MY_DATASETS' | 'CATALOG' | 'LLM' | 'BOT' | 'API' | 'SECRETS' | 'DIAGNOSTICS'>('SOURCES');
  const [activeSourceSubTab, setActiveSourceSubTab] = useState<'CUSTOMS' | 'TAX' | 'FILES' | 'WEB'>('CUSTOMS');
  const [isLoading, setIsLoading] = useState(false);
  const [refreshKey, setRefreshKey] = useState(0);

  // Data State
  const [secrets, setSecrets] = useState<IntegrationSecret[]>([]);
  const [files, setFiles] = useState<DataSourceFile[]>([]);
  const [webSources, setWebSources] = useState<DataSourceWeb[]>([]);
  const [apiSources, setApiSources] = useState<DataSourceAPI[]>([]);
  const [telegramBots, setTelegramBots] = useState<TelegramBotConfig[]>([]);
  const [llmConfig, setLlmConfig] = useState<LLMConfig | null>(null);
  const [activeSecretCategory, setActiveSecretCategory] = useState<'ALL' | 'GOV' | 'LLM' | 'BOT' | 'INFRA' | 'CYBER'>('ALL');
  
  // Data Hub State
  const [dataCatalog, setDataCatalog] = useState<DataCatalogItem[]>([]);
  const [userTemplates, setUserTemplates] = useState<UserDatasetTemplate[]>([]);
  const [autoDatasets, setAutoDatasets] = useState<AutoGeneratedDataset[]>([]);
  
  // Wizard State
  const [isWizardOpen, setIsWizardOpen] = useState(false);
  const [wizardStep, setWizardStep] = useState(1);
  const [wizardData, setWizardData] = useState<WizardData>({});

  // Diagnostics
  const [diagRunning, setDiagRunning] = useState(false);
  const [diagSteps, setDiagSteps] = useState([
      { id: 'vault', label: 'HashiCorp Vault Seal Status', status: 'PENDING' },
      { id: 'ext_sec', label: 'External Secrets Operator', status: 'PENDING' },
      { id: 'k8s_sync', label: 'K3s Secret Injection', status: 'PENDING' },
      { id: 'customs_api', label: 'Customs API Connectivity', status: 'PENDING' },
      { id: 'tax_api', label: 'Tax Service Connectivity', status: 'PENDING' },
      { id: 'llm_hub', label: 'LLM Gateway Latency', status: 'PENDING' },
  ]);

  const isMounted = useRef(false);

  useEffect(() => {
    isMounted.current = true;
    const fetchData = async () => {
        if (isMounted.current) setIsLoading(true);
        try {
            const [secData, fileData, webData, apiData, botData, llmCfg, catData, tplData, autoData] = await Promise.all([
                api.getSecrets(),
                api.getIntegrationSources('FILE'),
                api.getIntegrationSources('WEB'),
                api.getIntegrationSources('API'),
                api.getTelegramBots(),
                api.getLLMConfig(),
                api.getDataCatalog(),
                api.getUserTemplates(),
                api.getAutoDatasets()
            ]);
            if (isMounted.current) {
                setSecrets(secData);
                setFiles(fileData as DataSourceFile[]);
                setWebSources(webData as DataSourceWeb[]);
                setApiSources(apiData as DataSourceAPI[]);
                setTelegramBots(botData);
                setLlmConfig(llmCfg);
                setDataCatalog(catData);
                setUserTemplates(tplData);
                setAutoDatasets(autoData);
            }
        } catch (e) {
            console.error(e);
        } finally {
            if (isMounted.current) setIsLoading(false);
        }
    };
    fetchData();
    return () => { isMounted.current = false; };
  }, [refreshKey]);

  // Handlers
  const handleSaveSecret = async (secret: IntegrationSecret, value: string) => {
      setSecrets(prev => prev.map(s => s.id === secret.id ? { ...s, status: 'SYNCING' } : s));
      try {
          await api.saveSecret(secret.id, value);
          setTimeout(() => {
              if (isMounted.current) {
                  setSecrets(prev => prev.map(s => s.id === secret.id ? { ...s, status: 'ACTIVE', lastChecked: 'Just now' } : s));
              }
          }, 1500);
      } catch (e) {
          setSecrets(prev => prev.map(s => s.id === secret.id ? { ...s, status: 'INVALID' } : s));
      }
  };

  const handleTestSecret = async (secret: IntegrationSecret) => {
      try {
          await api.validateSecret(secret.id, 'test');
          setSecrets(prev => prev.map(s => s.id === secret.id ? { ...s, lastChecked: 'Just now' } : s));
      } catch (e) {
          console.error(e);
      }
  };

  const runDiagnostics = () => {
      if (diagRunning) return;
      setDiagRunning(true);
      setDiagSteps(prev => prev.map(s => ({ ...s, status: 'PENDING' })));

      let stepIndex = 0;
      const interval = setInterval(() => {
          if (stepIndex >= diagSteps.length) {
              clearInterval(interval);
              setDiagRunning(false);
              return;
          }
          setDiagSteps(prev => {
              const newSteps = [...prev];
              newSteps[stepIndex].status = Math.random() > 0.1 ? 'SUCCESS' : 'FAILURE';
              return newSteps;
          });
          stepIndex++;
      }, 600);
  };

  const getWizardStepContent = () => {
      switch(wizardStep) {
          case 1:
              return (
                  <div className="grid grid-cols-2 gap-4">
                      {['FILE', 'API', 'WEB', 'REGISTRY'].map((type) => (
                          <button 
                            key={type}
                            onClick={() => setWizardData({...wizardData, type: type as any})}
                            className={`p-6 border rounded-lg flex flex-col items-center justify-center gap-3 transition-all btn-3d ${
                                wizardData.type === type 
                                ? 'bg-primary-900/20 border-primary-500 text-primary-400 ring-2 ring-primary-500/50' 
                                : 'bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-500 hover:bg-slate-800'
                            }`}
                          >
                              {type === 'FILE' && <FileText size={32} />}
                              {type === 'API' && <Cable size={32} />}
                              {type === 'WEB' && <Globe size={32} />}
                              {type === 'REGISTRY' && <Building2 size={32} />}
                              <span className="font-bold text-sm">{type === 'FILE' ? 'Файл (Excel/CSV)' : type === 'API' ? 'Зовнішнє API' : type === 'WEB' ? 'Telegram/Web' : 'Держ. Реєстр'}</span>
                          </button>
                      ))}
                  </div>
              );
          case 2:
              return (
                  <div className="space-y-4">
                      <div>
                          <label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Назва Джерела</label>
                          <input 
                            type="text" 
                            className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-sm text-slate-200 focus:border-primary-500 outline-none"
                            value={wizardData.name || ''}
                            onChange={(e) => setWizardData({...wizardData, name: e.target.value})}
                            placeholder="Напр: Річні звіти 2023"
                          />
                      </div>
                      {wizardData.type === 'FILE' && (
                          <div className="border-2 border-dashed border-slate-700 rounded-lg p-8 flex flex-col items-center justify-center text-slate-500 hover:border-primary-500 hover:text-primary-400 transition-colors cursor-pointer bg-slate-900/50">
                              <UploadCloud size={32} className="mb-2"/>
                              <span className="text-xs font-bold">Перетягніть файл сюди або клікніть</span>
                          </div>
                      )}
                      {(wizardData.type === 'API' || wizardData.type === 'REGISTRY') && (
                          <div>
                              <label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Секрет (Vault Reference)</label>
                              <select className="w-full bg-slate-950 border border-slate-700 rounded p-2 text-sm text-slate-200 focus:border-primary-500 outline-none">
                                  <option value="">Виберіть ключ...</option>
                                  {secrets.map(s => <option key={s.id} value={s.id}>{s.name} ({s.keyName})</option>)}
                              </select>
                          </div>
                      )}
                  </div>
              );
          case 3:
              return (
                  <div className="h-[250px] flex items-center justify-center border border-slate-800 rounded bg-slate-900 text-slate-500">
                      <div className="text-center">
                          <Table size={48} className="mx-auto mb-4 opacity-20"/>
                          <p className="text-xs">Авто-визначення схеми (Schema Inference)...</p>
                      </div>
                  </div>
              );
          case 4:
              return (
                  <div className="grid grid-cols-2 gap-4">
                      {['GOV', 'BIZ', 'MED', 'SCI', 'OSINT', 'GENERAL'].map((sector) => (
                          <button 
                            key={sector}
                            onClick={() => setWizardData({...wizardData, classification: { ...wizardData.classification, sector: sector as DataSector, isCritical: wizardData.classification?.isCritical ?? false, forTraining: wizardData.classification?.forTraining ?? false }})}
                            className={`p-4 border rounded-lg text-center transition-all btn-3d ${
                                wizardData.classification?.sector === sector
                                ? 'bg-primary-900/20 border-primary-500 text-primary-400' 
                                : 'bg-slate-900 border-slate-700 text-slate-400'
                            }`}
                          >
                              <span className="font-bold text-xs">{sector}</span>
                          </button>
                      ))}
                  </div>
              );
          case 5:
              return (
                  <div className="space-y-4">
                      <div className="p-4 bg-slate-900 border border-slate-800 rounded flex items-center justify-between">
                          <span className="text-sm text-slate-200">Режим Оновлення</span>
                          <select className="bg-slate-950 border border-slate-700 rounded p-1 text-xs text-slate-300">
                              <option>За Розкладом (Cron)</option>
                              <option>Потокове (Stream)</option>
                              <option>Вручну</option>
                          </select>
                      </div>
                      <div className="p-4 bg-slate-900 border border-slate-800 rounded flex items-center justify-between">
                          <span className="text-sm text-slate-200">Включити в "Ранкову Газету"</span>
                          <input type="checkbox" className="accent-primary-500 w-4 h-4"/>
                      </div>
                  </div>
              );
          default: return null;
      }
  };

  // --- RENDERERS ---

  const renderDataSources = () => (
      <div className="space-y-6 animate-in fade-in duration-300">
          <Modal 
            isOpen={isWizardOpen} 
            onClose={() => setIsWizardOpen(false)} 
            title="Додати Нове Джерело Даних"
            icon={<Plus size={20} className="text-primary-400 icon-3d-blue"/>}
            size="lg"
          >
              <div className="p-6">
                  {/* Progress */}
                  <div className="flex justify-between items-center relative mb-8 px-8">
                      <div className="absolute top-4 left-0 w-full h-0.5 bg-slate-800 -z-0"></div>
                      <WizardStep num={1} title="Тип" active={wizardStep === 1} completed={wizardStep > 1} />
                      <WizardStep num={2} title="Параметри" active={wizardStep === 2} completed={wizardStep > 2} />
                      <WizardStep num={3} title="Схема" active={wizardStep === 3} completed={wizardStep > 3} />
                      <WizardStep num={4} title="Сектор" active={wizardStep === 4} completed={wizardStep > 4} />
                      <WizardStep num={5} title="Розклад" active={wizardStep === 5} completed={wizardStep > 5} />
                  </div>

                  {/* Content */}
                  <div className="min-h-[300px]">
                      {getWizardStepContent()}
                  </div>

                  {/* Actions */}
                  <div className="flex justify-between pt-6 border-t border-slate-800 mt-4">
                      <button onClick={() => setWizardStep(prev => Math.max(1, prev - 1))} className="px-6 py-2 bg-slate-800 rounded text-xs font-bold btn-3d text-slate-300" disabled={wizardStep === 1}>Назад</button>
                      {wizardStep < 5 ? (
                          <button onClick={() => setWizardStep(prev => prev + 1)} className="px-6 py-2 bg-primary-600 text-white rounded text-xs font-bold btn-3d btn-3d-blue">Далі</button>
                      ) : (
                          <button onClick={() => { setIsWizardOpen(false); setWizardStep(1); }} className="px-6 py-2 bg-green-600 text-white rounded text-xs font-bold btn-3d btn-3d-green">Створити Пайплайн</button>
                      )}
                  </div>
              </div>
          </Modal>

          {/* Sub-Tabs for Sources */}
          <div className="flex gap-2 border-b border-slate-800 pb-2 overflow-x-auto scrollbar-hide">
              {[
                  { id: 'CUSTOMS', label: 'Митні Декларації', icon: <ShieldCheck size={14}/> },
                  { id: 'TAX', label: 'Податкові Накладні', icon: <Building2 size={14}/> },
                  { id: 'FILES', label: 'Файли (Excel/PDF)', icon: <FileText size={14}/> },
                  { id: 'WEB', label: 'Web/OSINT', icon: <Globe size={14}/> },
              ].map(tab => (
                  <button
                      key={tab.id}
                      onClick={() => setActiveSourceSubTab(tab.id as any)}
                      className={`px-3 py-2 rounded-t-lg text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-all border-b-2 ${
                          activeSourceSubTab === tab.id 
                          ? 'border-primary-500 text-primary-400 bg-slate-900' 
                          : 'border-transparent text-slate-500 hover:text-slate-300'
                      }`}
                  >
                      {tab.icon} {tab.label}
                  </button>
              ))}
          </div>

          {activeSourceSubTab === 'CUSTOMS' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <TacticalCard title="Реєстр Митних Декларацій" className="panel-3d">
                      <div className="space-y-4">
                          <div className="p-4 bg-slate-950 border border-slate-800 rounded flex items-start gap-4">
                              <div className="p-3 bg-blue-900/20 rounded border border-blue-900/50 text-blue-400">
                                  <Shield size={24} />
                              </div>
                              <div className="flex-1">
                                  <h4 className="font-bold text-slate-200 text-sm">ДМСУ (Єдине Вікно)</h4>
                                  <p className="text-xs text-slate-500 mb-2">Автоматичний імпорт МД через API SW4.</p>
                                  <div className="flex gap-2 text-[10px]">
                                      <span className="px-2 py-0.5 bg-success-900/20 text-success-500 rounded border border-success-900/50">ONLINE</span>
                                      <span className="px-2 py-0.5 bg-slate-900 text-slate-400 rounded border border-slate-800">Synced: 10m ago</span>
                                  </div>
                              </div>
                              <button className="p-2 bg-slate-800 hover:bg-slate-700 rounded text-slate-400 transition-colors btn-3d"><RefreshCw size={14}/></button>
                          </div>
                          
                          <div className="space-y-2">
                              <label className="text-xs font-bold text-slate-500 uppercase">Налаштування Підключення</label>
                              <div className="grid grid-cols-2 gap-2">
                                  <div className="bg-slate-900 p-2 rounded border border-slate-800 text-xs">
                                      <span className="text-slate-500 block text-[9px] uppercase">Auth Method</span>
                                      <span className="text-slate-200 font-mono">EDS Key (Token)</span>
                                  </div>
                                  <div className="bg-slate-900 p-2 rounded border border-slate-800 text-xs">
                                      <span className="text-slate-500 block text-[9px] uppercase">Schedule</span>
                                      <span className="text-slate-200 font-mono">Real-time (Stream)</span>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </TacticalCard>
                  
                  <div className="space-y-4">
                      <div className="p-4 bg-yellow-900/10 border border-yellow-500/30 rounded flex items-start gap-3">
                          <AlertTriangle size={18} className="text-yellow-500 shrink-0 mt-0.5" />
                          <div>
                              <h4 className="text-sm font-bold text-yellow-500">Увага: ЕЦП Ключ</h4>
                              <p className="text-xs text-yellow-200/70 mt-1">
                                  Ключ ЕЦП для доступу до митниці потрібно оновлювати кожні 3 місяці. 
                                  Перейдіть у вкладку "Секрети" для завантаження нового .dat файлу.
                              </p>
                          </div>
                      </div>
                  </div>
              </div>
          )}

          {activeSourceSubTab === 'FILES' && (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {files.map(file => (
                      <div key={file.id} className="bg-slate-900 border border-slate-800 p-4 rounded group hover:border-blue-500/30 transition-colors panel-3d">
                          <div className="flex justify-between items-start mb-2">
                              <FileIcon size={20} className="text-blue-400" />
                              <button className="text-slate-500 hover:text-red-400"><Trash2 size={14}/></button>
                          </div>
                          <div className="text-sm font-bold text-slate-200 truncate" title={file.name}>{file.name}</div>
                          <div className="text-[10px] text-slate-500 mb-2">{file.size} • {file.format}</div>
                          <div className="flex gap-1">
                              {file.flags.minio && <span className="text-[9px] bg-slate-950 px-1.5 py-0.5 rounded border border-slate-800 text-slate-400">S3</span>}
                              {file.flags.openSearch && <span className="text-[9px] bg-slate-950 px-1.5 py-0.5 rounded border border-slate-800 text-slate-400">Index</span>}
                          </div>
                      </div>
                  ))}
                  <button 
                    onClick={() => { setIsWizardOpen(true); setWizardStep(1); }}
                    className="border border-dashed border-slate-800 rounded flex flex-col items-center justify-center text-slate-500 hover:border-slate-600 hover:text-slate-400 p-4 transition-colors min-h-[120px] btn-3d"
                  >
                      <Plus size={24} />
                      <span className="text-xs font-bold mt-2">Додати Джерело (Wizard)</span>
                  </button>
              </div>
          )}
      </div>
  );

  const renderMyDatasets = () => (
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in duration-300">
          <TacticalCard title="Шаблони Користувача (Manual Uploads)" className="panel-3d" action={<button className="text-slate-500 hover:text-white" onClick={() => {setIsWizardOpen(true); setWizardStep(1);}}><Plus size={14}/></button>}>
              <div className="space-y-3">
                  <p className="text-xs text-slate-500 mb-2">
                      Завантажені вами файли, які слугують "інструкцією" для авто-генерації майбутніх датасетів.
                  </p>
                  {userTemplates.map(tpl => (
                      <div key={tpl.id} className="p-3 bg-slate-900 border border-slate-800 rounded flex justify-between items-center group hover:border-slate-700 transition-colors">
                          <div className="flex items-center gap-3">
                              <div className={`p-2 rounded ${tpl.sector === 'BIZ' ? 'bg-yellow-900/20 text-yellow-500' : 'bg-slate-800 text-slate-500'}`}>
                                  <FileCode size={16} />
                              </div>
                              <div>
                                  <div className="text-xs font-bold text-slate-200">{tpl.name}</div>
                                  <div className="text-[10px] text-slate-500 font-mono">{tpl.fileType} • {tpl.rows} rows • {tpl.lastSync}</div>
                              </div>
                          </div>
                          {tpl.autoGenEnabled && (
                              <span className="text-[9px] bg-blue-900/20 text-blue-400 px-2 py-0.5 rounded border border-blue-900/50 uppercase font-bold animate-pulse">Auto-Gen</span>
                          )}
                      </div>
                  ))}
              </div>
          </TacticalCard>

          <TacticalCard title="Авто-Згенеровані Датасети (NAS Pipeline)" className="panel-3d">
              <div className="space-y-3">
                  <p className="text-xs text-slate-500 mb-2">
                      Датасети, створені системою автоматично на базі ваших шаблонів та нових даних з джерел.
                  </p>
                  {autoDatasets.map(ds => (
                      <div key={ds.id} className="p-3 bg-slate-900 border border-slate-800 rounded flex justify-between items-center group hover:border-purple-500/30 transition-colors">
                          <div className="flex items-center gap-3">
                              <div className="p-2 bg-purple-900/20 text-purple-500 rounded">
                                  <Database size={16} />
                              </div>
                              <div>
                                  <div className="text-xs font-bold text-slate-200">{ds.name}</div>
                                  <div className="text-[10px] text-slate-500 font-mono">
                                      Base: {ds.templateName || ds.sourceTemplateId} • {ds.rows} rows
                                  </div>
                              </div>
                          </div>
                          <div className="text-right">
                              <div className={`text-[9px] font-bold uppercase ${ds.status === 'READY' ? 'text-success-500' : 'text-yellow-500'}`}>{ds.status}</div>
                              {ds.usedInGazette && <div className="text-[9px] text-slate-500 flex items-center justify-end gap-1"><Check size={8}/> Gazette</div>}
                          </div>
                      </div>
                  ))}
              </div>
          </TacticalCard>
      </div>
  );

  const renderDataCatalog = () => (
      <div className="space-y-6 animate-in fade-in duration-300">
          <TacticalCard title="Центральний Каталог Даних (Data Lake)" className="panel-3d" action={<Search size={14} className="text-slate-500"/>}>
              <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                      <thead>
                          <tr className="text-[10px] text-slate-500 uppercase border-b border-slate-800 bg-slate-900/50">
                              <th className="p-3">Назва Активу</th>
                              <th className="p-3">Категорія</th>
                              <th className="p-3">Тип</th>
                              <th className="p-3">Рівень</th>
                              <th className="p-3">Якість</th>
                              <th className="p-3">Власник</th>
                              <th className="p-3 text-right">Статус</th>
                          </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800 text-xs">
                          {dataCatalog.map(item => (
                              <tr key={item.id} className="hover:bg-slate-800/30 transition-colors group cursor-pointer">
                                  <td className="p-3">
                                      <div className="font-bold text-slate-200">{item.name}</div>
                                      <div className="text-[10px] text-slate-500 truncate max-w-[200px]">{item.description}</div>
                                  </td>
                                  <td className="p-3">
                                      <span className={`px-2 py-0.5 rounded text-[9px] font-bold border ${
                                          item.category === 'GOV' ? 'bg-blue-900/20 text-blue-400 border-blue-900/50' :
                                          item.category === 'BIZ' ? 'bg-yellow-900/20 text-yellow-400 border-yellow-900/50' :
                                          item.category === 'MED' ? 'bg-red-900/20 text-red-400 border-red-900/50' :
                                          'bg-slate-800 text-slate-400 border-slate-700'
                                      }`}>
                                          {item.category}
                                      </span>
                                  </td>
                                  <td className="p-3 font-mono text-[10px]">{item.type}</td>
                                  <td className="p-3">
                                      <span className={`text-[9px] font-bold ${
                                          item.layer === 'GOLD' ? 'text-yellow-400 text-glow-amber' :
                                          item.layer === 'SILVER' ? 'text-slate-300' :
                                          'text-orange-700'
                                      }`}>
                                          {item.layer}
                                      </span>
                                  </td>
                                  <td className="p-3">
                                                                            <div className="w-16 h-1.5 bg-slate-900 rounded-full overflow-hidden">
                                                                                    <progress
                                                                                        value={item.qualityScore}
                                                                                        max={100}
                                                                                        aria-label={`Quality ${item.qualityScore}%`}
                                                                                        className={`w-full h-1.5 appearance-none ${item.qualityScore > 90 ? 'bg-green-500' : 'bg-yellow-500'} rounded`}
                                                                                    />
                                                                            </div>
                                  </td>
                                  <td className="p-3 text-slate-400">{item.owner}</td>
                                  <td className="p-3 text-right">
                                      <span className={`text-[9px] font-bold ${item.status === 'LIVE' ? 'text-success-500' : 'text-slate-500'}`}>
                                          {item.status}
                                      </span>
                                  </td>
                              </tr>
                          ))}
                      </tbody>
                  </table>
              </div>
          </TacticalCard>
      </div>
  );

  const renderLLM = () => (
      <div className="space-y-6 animate-in fade-in duration-300">
          <TacticalCard title="NAS / Brain Configuration" className="panel-3d">
              <div className="space-y-6">
                  <div className="bg-slate-950 border border-slate-800 rounded p-4">
                      <div className="flex justify-between items-center mb-4">
                          <h4 className="text-sm font-bold text-slate-200 flex items-center gap-2">
                              <BrainCircuit size={16} className="text-purple-500"/> Neural Brain Swarm
                          </h4>
                          <span className="text-[10px] bg-slate-900 px-2 py-1 rounded border border-slate-700 text-slate-400">Arbiter: Gemini 3 Ultra</span>
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {llmConfig?.providers.filter(p => p.priority <= 3).map(p => (
                              <div key={p.id} className="flex items-center justify-between p-3 bg-slate-900 rounded border border-slate-800">
                                  <div className="flex items-center gap-3">
                                      <div className={`w-3 h-3 rounded-full ${p.status === 'ACTIVE' ? 'bg-success-500 shadow-[0_0_5px_lime]' : 'bg-slate-600'}`}></div>
                                      <div className="text-xs font-bold text-slate-300">{p.name}</div>
                                  </div>
                                  <span className="text-[10px] font-mono text-slate-500">{p.model}</span>
                              </div>
                          ))}
                      </div>
                  </div>

                  <div className="p-4 bg-purple-900/10 border border-purple-900/30 rounded flex items-center justify-between">
                      <div>
                          <div className="text-sm font-bold text-purple-400 mb-1">Режим Конкуренції (Debate Mode)</div>
                          <div className="text-xs text-slate-400">NAS запускає 3 моделі паралельно та вибирає кращу відповідь.</div>
                      </div>
                      <div className="flex items-center gap-2">
                          <span className="text-xs font-bold text-white">ON</span>
                          <div className="w-8 h-4 bg-purple-600 rounded-full relative cursor-pointer shadow-[0_0_10px_#a855f7]">
                              <div className="absolute right-0.5 top-0.5 w-3 h-3 bg-white rounded-full"></div>
                          </div>
                      </div>
                  </div>
              </div>
          </TacticalCard>
      </div>
  );

  const renderSecrets = () => {
        const filteredSecrets = activeSecretCategory === 'ALL' 
            ? secrets 
            : secrets.filter(s => s.category === activeSecretCategory);

        return (
            <div className="space-y-6 animate-in fade-in duration-300">
                <div className="flex gap-2 border-b border-slate-800 pb-2 mb-4 overflow-x-auto scrollbar-hide">
                    {[
                        { id: 'ALL', label: 'Всі', icon: <Key size={14}/> },
                        { id: 'GOV', label: 'Державні Реєстри', icon: <Building2 size={14}/> },
                        { id: 'LLM', label: 'AI & Neural', icon: <BrainCircuit size={14}/> },
                        { id: 'BOT', label: 'Telegram', icon: <MessageSquare size={14}/> },
                        { id: 'INFRA', label: 'Інфраструктура (Oracle)', icon: <Server size={14}/> },
                        { id: 'CYBER', label: 'Кібербезпека', icon: <ShieldAlert size={14}/> },
                    ].map(cat => (
                        <button
                            key={cat.id}
                            onClick={() => setActiveSecretCategory(cat.id as any)}
                            className={`px-3 py-1.5 rounded text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-all border ${
                                activeSecretCategory === cat.id 
                                ? 'bg-primary-900/20 text-primary-400 border-primary-500/50' 
                                : 'bg-slate-900 text-slate-500 border-transparent hover:text-slate-300'
                            }`}
                        >
                            {cat.icon} {cat.label}
                        </button>
                    ))}
                </div>

                <div className="grid grid-cols-1 gap-4">
                    {filteredSecrets.map(secret => (
                        <SecretRow 
                            key={secret.id} 
                            secret={secret} 
                            onTest={handleTestSecret} 
                            onSave={handleSaveSecret} 
                        />
                    ))}
                </div>
                
                <div className="p-4 bg-slate-900/50 border border-slate-800 rounded flex items-start gap-3 mt-4">
                    <Lock size={16} className="text-yellow-500 mt-0.5 shrink-0" />
                    <div className="text-xs text-slate-400">
                        <strong className="text-slate-300">Протокол Безпеки G-01:</strong> Ключі не зберігаються у браузері. Вони шифруються та надсилаються безпосередньо у HashiCorp Vault.
                    </div>
                </div>
            </div>
        );
  };

  const renderDiagnostics = () => (
      <TacticalCard title="Діагностика Інтеграцій" className="panel-3d">
          <div className="space-y-6">
              <div className="flex justify-between items-center bg-slate-950 p-4 rounded border border-slate-800 shadow-inner">
                  <div>
                      <h3 className="font-bold text-slate-200">Перевірка Доступності API</h3>
                      <p className="text-xs text-slate-500">Ping external endpoints & Vault status</p>
                  </div>
                  <button 
                    onClick={runDiagnostics}
                    disabled={diagRunning}
                    className="px-6 py-2 bg-primary-600 hover:bg-primary-500 disabled:opacity-50 text-white text-xs font-bold rounded flex items-center gap-2 transition-all shadow-lg btn-3d btn-3d-blue"
                  >
                      {diagRunning ? <RefreshCw size={14} className="animate-spin" /> : <Activity size={14} />}
                      {diagRunning ? 'TESTING...' : 'RUN TESTS'}
                  </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {diagSteps.map((step, idx) => (
                      <div key={idx} className="flex items-center justify-between p-3 bg-slate-900 border border-slate-800 rounded panel-3d">
                          <div className="flex items-center gap-3">
                              <div className={`p-2 rounded-full ${
                                  step.status === 'SUCCESS' ? 'bg-success-900/20 text-success-500' :
                                  step.status === 'FAILURE' ? 'bg-red-900/20 text-red-500' :
                                  'bg-slate-800 text-slate-500'
                              }`}>
                                  {step.status === 'SUCCESS' ? <Check size={14} className="icon-3d-green" /> :
                                   step.status === 'FAILURE' ? <XCircle size={14} className="icon-3d-red" /> :
                                   <Activity size={14} className={diagRunning ? 'animate-pulse text-blue-500' : ''} />}
                              </div>
                              <span className={`text-xs font-bold ${step.status === 'PENDING' ? 'text-slate-500' : 'text-slate-300'}`}>
                                  {step.label}
                              </span>
                          </div>
                          <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${
                              step.status === 'SUCCESS' ? 'bg-success-900/10 text-success-500' :
                              step.status === 'FAILURE' ? 'bg-red-900/10 text-red-500' :
                              'bg-slate-800 text-slate-600'
                          }`}>
                              {step.status}
                          </span>
                      </div>
                  ))}
              </div>
          </div>
      </TacticalCard>
  );

  return (
    <div className="space-y-6 animate-in fade-in duration-500 pb-20 w-full max-w-[1600px] mx-auto">
        <ViewHeader 
            title="Центр Даних та Інтеграцій (Data Hub)"
            icon={<Database size={20} className="icon-3d-blue"/>}
            breadcrumbs={['SYSTEM', 'DATA CENTER', activeTab]}
            stats={[
                { label: 'Active Sources', value: String(files.length + webSources.length + apiSources.length), icon: <Globe size={14}/>, color: 'primary' },
                { label: 'Data Catalog', value: `${dataCatalog.length} ASSETS`, icon: <Table size={14}/>, color: 'success' },
                { label: 'Auto Datasets', value: `${autoDatasets.length} GEN`, icon: <Bot size={14}/>, color: 'purple' },
            ]}
        />

        {/* Main Tabs */}
        <div className="flex border-b border-slate-800 mb-6 bg-slate-950/30 rounded-t overflow-x-auto scrollbar-hide">
            {[
                { id: 'SOURCES', label: 'Джерела (Sources)', icon: <Cable size={16}/> },
                { id: 'MY_DATASETS', label: 'Мої Датасети (User)', icon: <Database size={16}/> },
                { id: 'CATALOG', label: 'Каталог Даних', icon: <Table size={16}/> },
                { id: 'LLM', label: 'LLM & Brain', icon: <BrainCircuit size={16}/> },
                { id: 'SECRETS', label: 'Секрети (Vault)', icon: <Key size={16}/> },
                { id: 'DIAGNOSTICS', label: 'Діагностика', icon: <Activity size={16}/> },
                { id: 'BOT', label: 'Telegram Бот', icon: <MessageSquare size={16}/> },
            ].map(tab => (
                <button 
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id as any)}
                    className={`flex-1 min-w-[120px] py-3 text-sm font-bold border-b-2 transition-colors flex items-center justify-center gap-2 ${
                        activeTab === tab.id 
                        ? 'border-primary-500 text-primary-400 bg-slate-800/30' 
                        : 'border-transparent text-slate-500 hover:bg-slate-800/30'
                    }`}
                >
                    {tab.icon} {tab.label}
                </button>
            ))}
        </div>

        <div className="min-h-[400px]">
            {isLoading && (
                <div className="absolute inset-0 flex items-center justify-center bg-slate-950/50 z-10">
                    <RefreshCw className="animate-spin text-primary-500" size={32} />
                </div>
            )}
            {activeTab === 'SOURCES' && renderDataSources()}
            {activeTab === 'MY_DATASETS' && renderMyDatasets()}
            {activeTab === 'CATALOG' && renderDataCatalog()}
            {activeTab === 'LLM' && renderLLM()}
            {activeTab === 'SECRETS' && renderSecrets()}
            {activeTab === 'DIAGNOSTICS' && renderDiagnostics()}
            {activeTab === 'BOT' && (
                <TacticalCard title="Telegram Bot Configuration" className="panel-3d">
                    <div className="p-4 text-center text-slate-500">
                        <MessageSquare size={48} className="mx-auto mb-4 opacity-20"/>
                        <p>Bot configuration interface placeholder.</p>
                    </div>
                </TacticalCard>
            )}
        </div>
    </div>
  );
};

export default IntegrationView;
