
import { 
    UAConnector, DataSourceFile, DataSourceWeb, DataSourceAPI, 
    LLMConfig, TelegramBotConfig, Agent, DatabaseTable, LogEntry,
    EtlJob, ServiceStatus, ClusterNode, AgentConfig,
    DeploymentEnvironment, PipelineRun, IntegrationSecret,
    DataCatalogItem, UserDatasetTemplate, AutoGeneratedDataset
} from '../types';

// --- INFRASTRUCTURE & DEPLOYMENT (The "Golden Standard" Setup) ---

export const MOCK_ENVIRONMENTS: DeploymentEnvironment[] = [
    { 
        id: 'dev-mac', 
        name: 'MacBook M3 (Dev)', 
        machineName: 'local-minikube', 
        clusterInfo: 'K3s v1.29.1', 
        ip: '192.168.64.2', 
        arch: 'arm64', 
        type: 'DEV', 
        status: 'ONLINE', 
        gitStatus: 'SYNCED', 
        version: 'v18.6.2-dev', 
        targetVersion: 'v18.6.2-dev', 
        lastSync: '10s ago', 
        progress: 100, 
        pods: [
            { id: 'p1', name: 'ua-sources', status: 'Running', ready: '1/1', restarts: 0, cpu: '12%', mem: '240Mi' },
            { id: 'p2', name: 'predator-backend', status: 'Running', ready: '1/1', restarts: 0, cpu: '8%', mem: '180Mi' },
            { id: 'p3', name: 'postgres-dev', status: 'Running', ready: '1/1', restarts: 0, cpu: '5%', mem: '512Mi' }
        ], 
        logs: [
            '[ArgoCD] Sync successful for "predator-dev"',
            '[Kubelet] Pulled image "ghcr.io/predator/backend:v18.6.2" (arm64)'
        ] 
    },
    { 
        id: 'prod-nvidia', 
        name: 'NVIDIA Server (Prod)', 
        machineName: 'srv-gtx1080-01', 
        clusterInfo: 'K3s v1.28.2+gpu', 
        ip: '10.0.0.50', 
        arch: 'amd64', 
        type: 'PROD', 
        status: 'ONLINE', 
        gitStatus: 'SYNCED', 
        version: 'v18.6.1', 
        targetVersion: 'v18.6.1', 
        lastSync: '2m ago', 
        progress: 100, 
        pods: [
            { id: 'p10', name: 'ua-sources', status: 'Running', ready: '2/2', restarts: 0, cpu: '45%', mem: '1.2Gi' },
            { id: 'p11', name: 'predator-backend', status: 'Running', ready: '3/3', restarts: 0, cpu: '25%', mem: '800Mi' },
            { id: 'p12', name: 'ollama-gpu', status: 'Running', ready: '1/1', restarts: 0, cpu: '10%', mem: '4.2Gi', gpu: true },
            { id: 'p13', name: 'qdrant-vector', status: 'Running', ready: '1/1', restarts: 1, cpu: '15%', mem: '2.1Gi' }
        ],
        logs: [
            '[NVIDIA] GPU 0: GeForce GTX 1080 (Utilization: 12%)',
            '[Kubelet] Pulled image "ghcr.io/predator/backend:v18.6.1" (amd64)'
        ]
    },
    { 
        id: 'canary-oracle', 
        name: 'Oracle Cloud (Canary)', 
        machineName: 'oracle-ampere-a1', 
        clusterInfo: 'K3s v1.29.0', 
        ip: '140.23.11.99', 
        arch: 'arm64', 
        type: 'CLOUD', 
        status: 'ONLINE', 
        gitStatus: 'SYNCING', 
        version: 'v18.6.0', 
        targetVersion: 'v18.6.2', 
        lastSync: 'Syncing...', 
        progress: 65, 
        pods: [
            { id: 'p20', name: 'ua-sources', status: 'ContainerCreating', ready: '0/1', restarts: 0, cpu: '0%', mem: '0Mi' },
            { id: 'p21', name: 'predator-backend', status: 'Running', ready: '1/1', restarts: 0, cpu: '15%', mem: '300Mi' }
        ],
        logs: [
            '[ArgoCD] Sync initiated for application "predator-canary"',
            '[Kubelet] Pulling image "ghcr.io/predator/backend:v18.6.2" (arm64)'
        ]
    }
];

export const MOCK_PIPELINES: PipelineRun[] = [
    {
        id: 'run-8921',
        status: 'SUCCESS',
        commitMessage: 'feat(ai): enable Gemini 3 Ultra support',
        branch: 'main',
        author: 'dkizyma',
        timestamp: '10 mins ago',
        duration: '2m 14s',
        type: 'FULL_DEPLOY',
        environments: { mac: true, nvidia: true, oracle: true },
        steps: [
            { name: 'Lint & Test', status: 'SUCCESS', duration: '45s' },
            { name: 'Build Multi-Arch (ARM64/AMD64)', status: 'SUCCESS', duration: '1m 20s' },
            { name: 'Push to GHCR', status: 'SUCCESS', duration: '15s' },
            { name: 'Update Helm Charts', status: 'SUCCESS', duration: '2s' },
            { name: 'ArgoCD Sync', status: 'SUCCESS', duration: '5s' }
        ]
    },
    {
        id: 'run-8920',
        status: 'SUCCESS',
        commitMessage: 'fix(etl): patch customs regex memory leak',
        branch: 'main',
        author: 'FixAgent',
        timestamp: '2 hours ago',
        duration: '1m 55s',
        type: 'FULL_DEPLOY',
        environments: { mac: true, nvidia: true, oracle: true },
        steps: [
            { name: 'Lint & Test', status: 'SUCCESS', duration: '40s' },
            { name: 'Build Multi-Arch (ARM64/AMD64)', status: 'SUCCESS', duration: '1m 10s' },
            { name: 'Push to GHCR', status: 'SUCCESS', duration: '12s' },
            { name: 'Update Helm Charts', status: 'SUCCESS', duration: '2s' },
            { name: 'ArgoCD Sync', status: 'SUCCESS', duration: '5s' }
        ]
    },
    {
        id: 'run-8919',
        status: 'FAILED',
        commitMessage: 'chore: update deps',
        branch: 'dev',
        author: 'renovate[bot]',
        timestamp: '5 hours ago',
        duration: '45s',
        type: 'TEST_ONLY',
        environments: { mac: true, nvidia: false, oracle: false },
        steps: [
            { name: 'Lint & Test', status: 'FAILED', duration: '45s' },
            { name: 'Build Multi-Arch', status: 'SKIPPED' },
            { name: 'Push to GHCR', status: 'SKIPPED' },
            { name: 'Update Helm Charts', status: 'SKIPPED' },
            { name: 'ArgoCD Sync', status: 'SKIPPED' }
        ]
    }
];

// --- OTHER MOCKS (Preserved) ---

export const MOCK_CONNECTORS: UAConnector[] = [
    { id: '1', name: 'ДМСУ (Customs)', category: 'GOV', authType: 'EDS (Key)', status: 'ONLINE', rpm: 120, latency: 45, endpoint: 'https://open-api.customs.gov.ua' },
    { id: '2', name: 'ДПС (Tax Service)', category: 'GOV', authType: 'OAuth2', status: 'ONLINE', rpm: 85, latency: 120, endpoint: 'https://cabinet.tax.gov.ua/api' },
    { id: '3', name: 'Prozorro Public', category: 'TENDERS', authType: 'API Key', status: 'ONLINE', rpm: 300, latency: 25, endpoint: 'https://public.api.openprocurement.org' },
    { id: '4', name: 'Opendatabot', category: 'REGISTRY', authType: 'API Key', status: 'ONLINE', rpm: 50, latency: 210, endpoint: 'https://opendatabot.com/api/v3' },
    { id: '5', name: 'YouControl', category: 'REGISTRY', authType: 'API Key', status: 'OFFLINE', rpm: 0, latency: 0, endpoint: 'https://api.youcontrol.com.ua' },
    { id: '6', name: 'NBU (Exchange)', category: 'FINANCE', authType: 'None', status: 'ONLINE', rpm: 10, latency: 15, endpoint: 'https://bank.gov.ua/NBUStatService' },
];

export const MOCK_FILES: DataSourceFile[] = [
    { id: 'f1', name: 'zvit_2023_q3.xlsx', format: 'EXCEL', category: 'BIZ', size: '1.2 MB', status: 'INDEXED', flags: { minio: true, openSearch: true, qdrant: false } },
    { id: 'f2', name: 'clients_export_nov.csv', format: 'CSV', category: 'BIZ', size: '45 MB', status: 'PROCESSING', flags: { minio: true, openSearch: false, qdrant: false } },
    { id: 'f3', name: 'contract_template.pdf', format: 'PDF', category: 'GOV', size: '240 KB', status: 'INDEXED', flags: { minio: true, openSearch: true, qdrant: true } },
];

export const MOCK_WEB_SOURCES: DataSourceWeb[] = [
    { id: 'w1', name: 'Telegram: @CustomsUA', url: 'https://t.me/CustomsUA', type: 'TELEGRAM', parser: 'Telethon', schedule: 'Real-time', status: 'ACTIVE', category: 'OSINT' },
    { id: 'w2', name: 'Web: Prozorro News', url: 'https://prozorro.gov.ua/news', type: 'WEBSITE', parser: 'Playwright', schedule: 'Every 1h', status: 'ACTIVE', category: 'GOV' },
];

export const MOCK_API_SOURCES: DataSourceAPI[] = [
    { id: 'a1', name: 'Nazk Declarations', baseUrl: 'https://public-api.nazk.gov.ua', authType: 'API_KEY', vaultSecret: 'nazk_token', status: 'ONLINE', category: 'GOV' },
];

export const MOCK_TELEGRAM_BOTS: TelegramBotConfig[] = [
    { id: 'b1', name: 'Predator Alert Bot', username: '@predator_alert_bot', description: 'Critical alerts channel', vaultTokenRef: 'bot_alert_token', webhookUrl: 'https://predator.internal/webhooks/telegram', whitelist: ['admin'], roles: ['ALERT'], status: 'ACTIVE', permissions: { clusterControl: false, healthAnalytics: true, osintAccess: false }, llmMode: 'AUTO' },
];

export const MOCK_LLM_CONFIG: LLMConfig = {
    mode: 'ROBUST_FALLBACK',
    providers: [
        { id: 'p1', name: 'Gemini 3 Ultra', type: 'CLOUD', model: 'gemini-3-ultra', vaultRef: 'gemini_key', priority: 1, status: 'ACTIVE', accountsCount: 3, rotationStrategy: 'ROUND_ROBIN', currentLoad: 45 },
        { id: 'p2', name: 'DeepSeek R1', type: 'CLOUD', model: 'deepseek-reasoner', vaultRef: 'deepseek_key', priority: 2, status: 'ACTIVE', accountsCount: 2, rotationStrategy: 'FAILOVER', currentLoad: 20 },
        { id: 'p3', name: 'Local Llama 3', type: 'LOCAL', model: 'llama-3-70b-quant', vaultRef: 'none', priority: 3, status: 'STANDBY', accountsCount: 1, rotationStrategy: 'ROUND_ROBIN', currentLoad: 0 },
        { id: 'p4', name: 'Mistral Large', type: 'FALLBACK', model: 'mistral-large', vaultRef: 'mistral_key', priority: 4, status: 'STANDBY', accountsCount: 1, rotationStrategy: 'FAILOVER', currentLoad: 0 },
    ],
    arbiter: { model: 'gemini-3-ultra', threshold: 0.85 }
};

export const MOCK_AGENTS: Agent[] = [
    { id: 'MED-01', name: 'Hippocrates', clan: 'INVESTIGATION', type: 'Medical AI', status: 'WORKING', efficiency: 94, lastAction: 'Indexing DICOM files' },
    { id: 'FIN-01', name: 'Gordon', clan: 'INVESTIGATION', type: 'Fin. Analyst', status: 'IDLE', efficiency: 97, lastAction: 'Standby' },
    { id: 'ECO-01', name: 'Gaia', clan: 'INVESTIGATION', type: 'Eco Scientist', status: 'IDLE', efficiency: 91, lastAction: 'Standby' },
    { id: 'SEC-01', name: 'Sherlock', clan: 'SECURITY', type: 'SecOps', status: 'WORKING', efficiency: 99, lastAction: 'Scanning logs' },
];

export const MOCK_DATABASES: DatabaseTable[] = [
    { id: 't1', name: 'ua_customs_declarations', type: 'TimescaleDB', records: 1420500, size: '4.2 GB', lastUpdated: '10m ago', status: 'ACTIVE' },
    { id: 't2', name: 'ua_tax_debts', type: 'PostgreSQL', records: 850000, size: '1.1 GB', lastUpdated: '1h ago', status: 'ACTIVE' },
    { id: 't3', name: 'ua_prozorro_tenders', type: 'PostgreSQL', records: 5200100, size: '12 GB', lastUpdated: '5m ago', status: 'ACTIVE' },
    { id: 't4', name: 'osint_telegram_messages', type: 'Elasticsearch', records: 15400000, size: '45 GB', lastUpdated: 'Real-time', status: 'ACTIVE' },
];

export const MOCK_SECURITY_LOGS: LogEntry[] = [
    { id: 'l1', timestamp: '2023-10-27 14:45:12', user: 'admin', action: 'Accessed Secret: ua_customs_key', ip: '10.0.1.5', status: 'SUCCESS' },
    { id: 'l2', timestamp: '2023-10-27 14:42:00', user: 'unknown', action: 'Failed Login Attempt', ip: '185.12.44.1', status: 'FAILURE' },
    { id: 'l3', timestamp: '2023-10-27 14:30:15', user: 'system', action: 'Vault Unseal', ip: 'localhost', status: 'SUCCESS' },
    { id: 'l4', timestamp: '2023-10-27 14:15:00', user: 'analyst_1', action: 'Exported Report: [PII MASKED]', ip: '10.0.2.10', status: 'SUCCESS' },
];

export const MOCK_WAF_LOGS = [
    { id: 'w1', time: '14:40:01', ip: '45.11.22.33', type: 'SQL Injection', action: 'BLOCKED' },
    { id: 'w2', time: '14:38:55', ip: '192.168.1.105', type: 'XSS Attempt', action: 'BLOCKED' },
    { id: 'w3', time: '14:35:12', ip: '88.12.11.9', type: 'Rate Limit Exceeded', action: 'THROTTLED' },
];

export const MOCK_TARGETS = [
    { id: 'tgt1', name: 'K3s Master', status: 'UP', latency: '2ms' },
    { id: 'tgt2', name: 'NVIDIA GPU', status: 'UP', latency: '1ms' },
    { id: 'tgt3', name: 'Oracle Cloud', status: 'UP', latency: '45ms' },
];

export const MOCK_ETL_JOBS: EtlJob[] = [
    { id: 'j1', pipeline: 'Sync Customs (Incremental)', status: 'SUCCESS', records: 1420, duration: '45s', timestamp: '14:00' },
    { id: 'j2', pipeline: 'Tax Debt Registry', status: 'RUNNING', records: 0, duration: '12s', timestamp: '14:30' },
    { id: 'j3', pipeline: 'OSINT Telegram Scraper', status: 'SUCCESS', records: 500, duration: '2m', timestamp: '14:15' },
    { id: 'j4', pipeline: 'Currency Rates NBU', status: 'SUCCESS', records: 32, duration: '1s', timestamp: '09:00' },
];

export const MOCK_SERVICES: ServiceStatus[] = [
    { name: 'PostgreSQL Primary', status: 'ONLINE', uptime: '14d', latency: 2 },
    { name: 'Qdrant Vector DB', status: 'ONLINE', uptime: '14d', latency: 5 },
    { name: 'Ollama (LLM)', status: 'ONLINE', uptime: '2d', latency: 45 },
    { name: 'Redis Cache', status: 'ONLINE', uptime: '14d', latency: 1 },
];

export const MOCK_CLUSTER: ClusterNode[] = [
    { name: 'k3s-master-01', role: 'CONTROL-PLANE', status: 'Ready', cpuUsage: 15, memUsage: 45, pods: [] },
    { name: 'k3s-gpu-01', role: 'WORKER', status: 'Ready', cpuUsage: 35, memUsage: 60, gpuUsage: 12, pods: [] },
    { name: 'k3s-oracle-01', role: 'WORKER', status: 'Ready', cpuUsage: 20, memUsage: 30, pods: [] },
];

export const MOCK_VECTORS = Array.from({length: 50}, (_, i) => ({
    id: i,
    x: Math.random() * 100,
    y: Math.random() * 100,
    z: Math.random() * 100 + 50,
    cluster: i % 4 === 0 ? 'GOV' : i % 4 === 1 ? 'MED' : i % 4 === 2 ? 'BIZ' : 'SCI'
}));

export const MOCK_SECTOR_DATA = {
    GOV: {
        ticker: ["Митниця: затримка на кордоні 'Ягодин' +4г", "Рада: прийнято закон про мобілізацію економіки", "ДПС: план перевірок на Q4 оновлено"],
        graphNodes: { A: 'ТОВ МегаБуд', B: 'Тендер #4421', C: 'Офшор Ltd', D: 'PEP: Іванов І.І.' }
    },
    MED: {
        ticker: ["МОЗ: спалах грипу в Одеській області", "Вакцинація: дефіцит КПК у регіоні #4", "eHealth: оновлення протоколу обміну"],
        graphNodes: { A: 'Пацієнт Zero', B: 'Лікарня #1', C: 'Аптека "Здоров\'я"', D: 'Склад вакцин' }
    },
    BIZ: {
        ticker: ["НБУ: курс USD/UAH 38.50", "SWIFT: затримка платежів у єврозоні", "Агро: ціни на соняшник +5%"],
        graphNodes: { A: 'ТОВ АгроТрейд', B: 'Транзакція $50k', C: 'Банк Кіпру', D: 'Контрагент X' }
    },
    SCI: {
        ticker: ["Екологія: перевищення PM2.5 у Києві", "Сейсмо: поштовхи 2.1 бали (Карпати)", "Гідро: рівень води в Дніпрі в нормі"],
        graphNodes: { A: 'Сенсор AQI-44', B: 'Завод "ХімПром"', C: 'Вітер: Пн-Зх', D: 'Район "Центр"' }
    }
};

export const MOCK_BENCHMARKS = [
    { id: 1, model: 'Gemini 2.0 Flash', task: 'NER Extraction', score: 98.2, speed: 120 },
    { id: 2, model: 'DeepSeek R1', task: 'Logic Reasoning', score: 94.5, speed: 45 },
    { id: 3, model: 'Llama 3 70B', task: 'Summarization', score: 91.0, speed: 30 },
];

export const MOCK_AUTOML_EXPERIMENTS = [
    { id: 'exp-101', name: 'Fraud Detection v2', status: 'RUNNING', score: 0.88, algo: 'XGBoost', target: 'Accuracy' },
    { id: 'exp-100', name: 'Credit Score v1', status: 'COMPLETED', score: 0.92, algo: 'LightGBM', target: 'AUC' },
];

export const MOCK_AGENT_CONFIGS: AgentConfig[] = [
    { id: 'a1', name: 'Sherlock (Sec)', role: 'Security Auditor', model: 'Gemini 2.0', permission: 'READ_ONLY', dailyBudgetUsd: 5.0, currentSpendUsd: 1.2, status: 'ACTIVE' },
    { id: 'a2', name: 'Coder (Dev)', role: 'Code Refactor', model: 'DeepSeek R1', permission: 'PROPOSE_PR', dailyBudgetUsd: 10.0, currentSpendUsd: 4.5, status: 'ACTIVE' },
];

export const MOCK_SECRETS: IntegrationSecret[] = [
    { id: 's1', name: 'Prozorro API Key', category: 'GOV', keyName: 'UA_PROZORRO_KEY', status: 'ACTIVE', lastChecked: '1h ago', description: 'Access to public tenders', vaultPath: 'external/prozorro' },
    { id: 's2', name: 'Gemini API Key', category: 'LLM', keyName: 'GOOGLE_AI_KEY', status: 'ACTIVE', lastChecked: '5m ago', description: 'Main LLM Engine', vaultPath: 'ai/google' },
    { id: 's3', name: 'Oracle Cloud Key', category: 'INFRA', keyName: 'OCI_KEY_FILE', status: 'ACTIVE', lastChecked: '1d ago', description: 'Infrastructure Control', vaultPath: 'infra/oracle', requiresFile: true },
];

export const MOCK_DATA_CATALOG: DataCatalogItem[] = [
    { id: 'dc1', name: 'Єдиний Державний Реєстр (ЄДР)', description: 'Повний перелік юридичних осіб та ФОП. Оновлення щоденно.', category: 'GOV', type: 'REGISTRY', status: 'LIVE', records: 1250000, lastUpdate: 'Today', qualityScore: 98, layer: 'GOLD', owner: 'MinJustice' },
    { id: 'dc2', name: 'Митні Декларації (Імпорт 2023)', description: 'Анонімізовані дані по імпорту товарів.', category: 'BIZ', type: 'DATASET', status: 'LIVE', records: 450000, lastUpdate: 'Yesterday', qualityScore: 92, layer: 'SILVER', owner: 'Customs Service' },
    { id: 'dc3', name: 'Telegram OSINT Stream', description: 'Моніторинг згадок ключових слів у 500+ каналах.', category: 'OSINT', type: 'STREAM', status: 'LIVE', records: 15400000, lastUpdate: 'Real-time', qualityScore: 75, layer: 'BRONZE', owner: 'Predator Bot' },
];

export const MOCK_USER_TEMPLATES: UserDatasetTemplate[] = [
    { id: 'tpl1', name: 'Мій Експорт Зерна 2023.xlsx', fileType: 'EXCEL', size: '2.4 MB', sector: 'BIZ', isTemplate: true, autoGenEnabled: true, lastSync: '2d ago', rows: 1420 },
    { id: 'tpl2', name: 'Чорний Список Контрагентів.csv', fileType: 'CSV', size: '45 KB', sector: 'GOV', isTemplate: true, autoGenEnabled: false, lastSync: '1w ago', rows: 55 },
];

export const MOCK_AUTO_DATASETS: AutoGeneratedDataset[] = [
    { id: 'gen1', name: 'AUTO: Експорт Зерна (Листопад)', sourceTemplateId: 'tpl1', templateName: 'Мій Експорт Зерна 2023.xlsx', rows: 150, status: 'READY', nextUpdate: 'Tomorrow', usedInGazette: true, sector: 'BIZ', updateFrequency: 'Daily' },
];
